clone the file named main.cpp.  After you have downloaded the file, you would have two option on how to executive this file.

a) You could compile and run it in you IDE. Using the IDE you would link and make an executable file, The IDE would build your execuable file
from this one file you have cloned. After that you can now run it using F1.
b) You could use the comand g++ filNamee.cpp fileName.cpp -0 fileName.exe. This command would create an executable file with all links
correctly assigned. Execution command: g++ main.cpp main.cpp -o main.exe

The result from the file execution should display some records of the successful execution in output file.
